# Generated by Django 5.2.7 on 2026-07-14 10:49

import apps.service_ingest.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("segment_event_name", models.CharField(max_length=255)),
                ("payload_type", models.CharField(choices=[("batch", "Batch"), ("event", "Event")], max_length=10)),
                ("collection_start", models.DateTimeField(blank=True, null=True)),
                ("collection_end", models.DateTimeField(blank=True, null=True)),
                ("event_timestamp", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "segment_anonymous_id",
                    models.CharField(default=apps.service_ingest.models._uuid4_str, max_length=64),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["service_name", "status"], name="service_ing_service_48ef89_idx"),
                    models.Index(fields=["payload_type", "status", "created"], name="service_ing_payload_32d5e9_idx"),
                ],
            },
        ),
    ]
