# Generated by Django 5.2.7 on 2026-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_ingest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="externalevent",
            name="modified_by",
        ),
        migrations.AlterField(
            model_name="externalevent",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="externalevent",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
